'use strict';

module.exports = {
  WX_HEADER_FLAG: 'X-WX-Flag',
  WX_HEADER_CODE: 'X-WX-Code',
  WX_HEADER_ENCRYPTED_DATA: 'X-WX-Encrypted-Data',
  WX_HEADER_IV: 'X-WX-IV',
  WX_HEADER_SKEY: 'X-WX-Skey',
  ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
  ERR_INVALID_SESSION: 'ERR_INVALID_SESSION',
};
